#ifndef EXTRA_ZEPHYR_INCLUDE_DT_BINDINGS_INPUT_INPUT_EVENT_CODES_H_
#define EXTRA_ZEPHYR_INCLUDE_DT_BINDINGS_INPUT_INPUT_EVENT_CODES_H_

#define BUTTON_0 60
#define BUTTON_1 61

#define HAT_BIT_UP 0
#define HAT_BIT_DOWN 1
#define HAT_BIT_LEFT 2
#define HAT_BIT_RIGHT 3
#define HAT_BIT_CLICK 4

#define HATSWITCH_UP 0x00
#define HATSWITCH_UPRIGHT 0x01
#define HATSWITCH_RIGHT 0x02
#define HATSWITCH_DOWNRIGHT 0x03
#define HATSWITCH_DOWN 0x04
#define HATSWITCH_DOWNLEFT 0x05
#define HATSWITCH_LEFT 0x06
#define HATSWITCH_UPLEFT 0x07
#define HATSWITCH_NONE 0x0F

#endif